Ejemplo canónico de módulos en Python
IslasGECI/dummy_transformations pull request #1
Opened 2020-06-08 19:05 UTC by islasfernando

Que falta para que este repositorio sea nuestro ejemplo canónico para módulos en Python.

2020-06-08 19:07 UTC, evaristor commented
@nepito Podrías echarle un ojo a esto?

2020-06-08 19:11 UTC, nepito requested changes
Mejora el formato del código

2020-06-08 19:11 UTC, nepito commented on dummy_transformations/transformations.py
> +
Por favor pásale el _black_ para darle formato a este archivo

2020-06-08 19:11 UTC, nepito commented on tests/test_transformations.py
> +
Por favor pásale el _black_ para darle formato a este archivo

2020-06-08 19:19 UTC, evaristor commented
@nepito @islasfernando:
Tal vez podamos usar el black como _pre-commit hook_ o en el _GHActions_?

2020-06-08 19:29 UTC, nepito commented
> @nepito @islasfernando:
> Tal vez podamos usar el black como _pre-commit hook_ o en el _GHActions_?

Cómo sería eso, antes de hacer un _commit_ primero pasaría el _black_ por los archivos o pediría como requisito el _black_ para permitir hacer el _commit_ u otra coso @evaristor ?

2020-06-08 21:01 UTC, evaristor commented
> Cómo sería eso, antes de hacer un _commit_ primero pasaría el _black_ por los archivos o pediría como requisito el _black_ para permitir hacer el _commit_ u otra coso @evaristor ?

Sí, algo así, @nepito. No estoy seguro. Tal vez no te dejaría consignar (o pushar?) si el _black_ "no pasa".

2020-06-08 21:05 UTC, nepito commented
> > Cómo sería eso, antes de hacer un _commit_ primero pasaría el _black_ por los archivos o pediría como requisito el _black_ para permitir hacer el _commit_ u otra coso @evaristor ?
> 
> Sí, algo así, @nepito. No estoy seguro. Tal vez no te dejaría consignar (o pushar?) si el _black_ "no pasa".

No sabía que el _black_ pasaba como prueba, pensé que solo cambiaba el formato (o le daba formato)

2020-06-08 23:17 UTC, evaristor commented
> No sabía que el _black_ pasaba como prueba, pensé que solo cambiaba el formato (o le daba formato)

@nepito: Yo tampoco sé eso. Les estoy preguntando a ti y al @islasfernando si se puede hacer eso.

2020-06-22 18:32 UTC, evaristor commented
¡Listo @nepito!
Por favor podrías revisarlo nuevamente?

2020-07-06 16:26 UTC, evaristor commented on tests/test_transformations.py
> +
Listo, @nepito. Por favor podrías revisarlo nuevamente?

2020-07-06 16:28 UTC, evaristor commented
@nepito: Ya atendimos tus comentarios.
Por favor podrías revisar este _PR_ nuevamente?

2020-07-06 18:16 UTC, nepito approved these changes
Listo @evaristor y @islasfernando

2020-07-06 18:16 UTC, nepito commented on Makefile
> +	codecov --token=6c56bccb-1758-4ed9-8161-97c845591c26
Este _token_ ¿cómo lo obtienes? ¿Es único por repositorio?

2020-07-06 18:17 UTC, evaristor commented
Gracias, @nepito.
Por favor podrías hacer _merge_ de la _release_ hacia la _master_?

2020-07-06 18:30 UTC, evaristor commented on Makefile
> +	codecov --token=6c56bccb-1758-4ed9-8161-97c845591c26
Sí, @nepito, es un token único por repositorio. Lo obtienes [aquí](https://codecov.io/gh/IslasGECI/dummy-transformations.py/settings).

2020-07-06 18:31 UTC, merged